# full - resized - wal - thumb -  fastresize - kmeans
backend = "wal"
# lab - labmixed - lch - lchmixed - salience
color_space = "lch"
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
# saliencedark - saliencedarkbalanced - saliencedarkdistributed - saliencedarklow (each has the 16 variations)
# salienceligh - saliencelightbalanced - saliencelightdistributed - saliencelightlow (each has the 16 variations)
palette = "saliencedark"
#check_contrast = true
#saturation = 35
#alpha = 100
#no_hooks = true

[templates]
# kdeglob = { src = 'kdeglobals', dst = '~/.config/kdeglobals'}
# walkvjsn= { src = 'kvwallust.json', dst = '~/.config/Kvantum/Wallust/Wallust.json' }
# walkvkvc= { src = 'kvwallust.kvconfig', dst = '~/.config/Kvantum/Wallust/Wallust.kvconfig' }
# walkvsvg= { src = 'kvwallust.svg', dst = '~/.config/Kvantum/Wallust/Wallust.svg', pywal = true }
copyq     = { src = 'copyq-wal.ini', dst = '~/.config/copyq/themes/copyq-wal.ini' }
dunst     = { src = 'dunstrc', dst = '~/.config/dunst/dunstrc' }
flameshot = { src = 'flameshot.ini', dst = '~/.config/flameshot/flameshot.ini' }
gtk3      = { src = 'gtk.css', dst = '~/.config/gtk-3.0/colors.css' }
gtk4      = { src = 'gtk.css', dst = '~/.config/gtk-4.0/colors.css' }
mango     = { src = 'mango-colors.conf', dst = '~/.config/mango/colors.conf' }
mpv       = { src = 'modernz.conf', dst = '~/.config/mpv/script-opts/modernz.conf' }
neopywal  = { src = 'colors_neopywal.vim', dst = '~/.cache/wallust/colors_neopywal.vim' }
polybar   = { src = 'colors-polybar.ini', dst = '~/.config/polybar/wal.ini' }
qimgv     = { src = 'qimgv-wal.conf', dst = '~/.config/qimgv/theme.conf' }
rmpc      = { src = 'rmpc-wal.ron', dst = '~/.config/rmpc/themes/wal.ron' }
rofi      = { src = 'colors-rofi.rasi', dst = '~/.config/rofi/colors/wal.rasi' }
sway      = { src = 'colors-sway', dst = '~/.config/sway/colors' }
swaylock  = { src = 'swaylock', dst = '~/.config/swaylock/config' }
vscode    = { src = 'vscode.json', dst = '~/.cache/wallust/colors.json' }
vscode2   = { src = 'vscode', dst = '~/.cache/wallust/colors' }
waybar    = { src = 'colors-waybar.css', dst = '~/.config/waybar/colors.css' }
wezterm   = { src = 'colors-wezterm.toml', dst = '~/.config/wezterm/colors/wal.toml' }
wofi      = { src = 'style-wofi.css', dst = '~/.config/wofi/style.css'}
xres      = { src = 'Xresources', dst = '~/.config/Xresources' }
zathura   = { src = 'zathurarc', dst = '~/.config/zathura/zathurarc' }

[hooks]
dunst   = '~/.config/wallust/hooks/dunst'
sway    = '~/.config/wallust/hooks/sway'
mangowm = '~/.config/wallust/hooks/mangowc'
notif   = 'notify-send "Colorscheme changed"'
