env=WALLPAPER,{{wallpaper}}
rootcolor=0x{{background | strip}}FF
bordercolor=0x{{color1 | strip}}FF
focuscolor=0x{{color5 | strip}}FF
urgentcolor=0x{{color7 | strip}}FF
globalcolor=0x{{color6 | strip}}FF
overlaycolor=0x{{color6 | strip}}FF
maximizescreencolor=0x{{color6 | strip}}FF
